export type DenueRawRecord = {
  id?: string;
  clee?: string;
  CLEE?: string;
  Id?: string;
  nom_estab?: string;
  Nombre?: string;
  raz_social?: string;
  Razon_social?: string;
  codigo_act?: string;
  Clase_actividad?: string;
  nombre_act?: string;
  per_ocu?: string;
  Estrato?: string;
  tipo_vial?: string;
  Tipo_vialidad?: string;
  nom_vial?: string;
  Calle?: string;
  numero_ext?: string;
  Num_Exterior?: string;
  Num_Interior?: string;
  nomb_asent?: string;
  Colonia?: string;
  cod_postal?: string;
  CP?: string;
  Ubicacion?: string;
  localidad?: string;
  municipio?: string;
  entidad?: string;
  telefono?: string;
  Telefono?: string;
  correoelec?: string;
  Correo_e?: string;
  www?: string;
  Sitio_internet?: string;
  tipoUniEco?: string;
  Tipo?: string;
  longitud?: string;
  Longitud?: string;
  latitud?: string;
  Latitud?: string;
  CentroComercial?: string;
  TipoCentroComercial?: string;
  NumLocal?: string;
  AGEB?: string;
  Manzana?: string;
  Edificio?: string;
  Clase_actividad_id?: string;
  Sector_actividad_id?: string;
  Subsector_actividad_id?: string;
  Rama_actividad_id?: string;
  Subrama_actividad_id?: string;
  CLASE_ACTIVIDAD_ID?: string;
  SECTOR_ACTIVIDAD_ID?: string;
  SUBSECTOR_ACTIVIDAD_ID?: string;
  RAMA_ACTIVIDAD_ID?: string;
  SUBRAMA_ACTIVIDAD_ID?: string;
  [key: string]: unknown;
};

export type NormalizedDenueRecord = {
  sourceRecordId: string;
  denueId: string | null;
  legalName: string | null;
  tradeName: string | null;
  normalizedName: string | null;
  website: string | null;
  websiteDomain: string | null;
  phone: string | null;
  normalizedPhone: string | null;
  email: string | null;
  street: string | null;
  city: string | null;
  municipality: string | null;
  state: string | null;
  postalCode: string | null;
  latitude: number | null;
  longitude: number | null;
  employeeSizeBand: string | null;
  industryCode: string | null;
  industryLabel: string | null;
  establishmentStatus: string | null;
  isManufacturingCandidate: boolean;
};
